### ISSUE TITLE
2 durability texts when worn tool and weapon

### ISSUE THREAD

**Issue by wnynya** [jho5245/Cucumbery#2]
New item:
![image](https://user-images.githubusercontent.com/52326888/131884572-97f7b869-89b0-4cd2-89f9-768d3fca8e6c.png)

Worn item:
![image](https://user-images.githubusercontent.com/52326888/131884027-667d79b8-fe61-4030-ba2d-0c64bf8e7001.png)

I think there needs to be shown only one durability text (coloured upper one). But it shows two durability texts when tools are worn out. It's weird. Is it intended way?

**Comment by gusen1116** [comment]
oh..... What is happen cucumbery? if my guess is right, it is a little bug.

**Comment by jho5245** [comment]
It is client side lore not my plugins bug. it cannot be fixed no matter what.
