### ISSUE TITLE
Cucumbery TMI bug(sign item) 

### ISSUE THREAD

**Issue by gusen1116** [jho5245/Cucumbery#3]
1번/ NO.1
![1](https://user-images.githubusercontent.com/83714769/132239599-0d8d0cfe-4a1e-48cc-a7ee-9823cde0b759.png)

**───────────────────────────────────────**

2번/ NO.2
![2](https://user-images.githubusercontent.com/83714769/132239603-5125e08f-d931-4182-8298-b0495bfaf525.png)

**───────────────────────────────────────**

3번/ NO.3
![3](https://user-images.githubusercontent.com/83714769/132239606-5bfb261b-cc83-4f4d-8ba3-bb1b5828dd19.png)

**───────────────────────────────────────**

4번/ NO.4
![4](https://user-images.githubusercontent.com/83714769/132239902-f0f8445b-3049-40e8-934d-65eeb20dafdd.png)

**───────────────────────────────────────**

5번/ NO.5
![5](https://user-images.githubusercontent.com/83714769/132239957-986aea8e-27ed-4702-8d45-e25fdf0c6abc.png)

**───────────────────────────────────────**

1번 ~ 3번까지 사진들은 표지판에 색깔 코드가 2개 이상 사용 했을 때 "n번째 텍스트" 아이템 설명이 제대로 작동하지 않습니다.
4번 ~ 5번까지 사진들은 이전과 색깔 코드가 2개 이상 사용 했을 때 앞선 문제와,  아이템 설명으로 보이는  "n번째 텍스트" 설명의 
 텍스트 색깔이 제대로 나오지 않습니다.

─────────────────────────────────────────────────

The "nth text" item description doesn't work properly when more than one color code is used for photos from 1 to 3.
Photographs from 4 to 5 have a previous problem and two or more color codes, and the "nth text" description that appears to be an item description, Its color is not coming out properly.
Thank you for reading my writing. 
If you want to hear/see more details, you contact me me anytime. I can always help you with pleasure.

**Comment by jho5245** [comment]
fixed
