### ISSUE TITLE
Chat overlay information hide 채팅 오버레이 정보 숨기기

### ISSUE THREAD

**Issue by bbforest** [jho5245/Cucumbery#6]
I think the information on the chat overlay is excessively displayed. I want to hide information such as coordinates and UUID. Please make a chat overlay information toggle.
채팅 오버레이의 정보가 과도하게 표시된다고 생각합니다. 좌표, UUID 등의 정보를 숨기고 싶습니다. 채팅 오버레이 정보 토글을 만들어주세요.

**Comment by jho5245** [comment]
이정도면 충분하지
